#+title: R review: managing data
#+author: [yourname]
#+startup: overview hideblocks indent
#+property: header-args:R :session *R* :exports both :results output
* README

This file covers main data structures in R:
- Vectors, or ordered n-tuples
- Factor vectors, or vectors for ordered or nominal categories
- Lists, or collections of any other R data structure
- Data frames, or a table of features (cols) and observations (rows)

Most of this material can be found in Lantz, Machine Learning with R
(3e, 2019), Packt. Solutions can be found in GitHub as PDF files.

* TODO Identify and pledge yourself

1) In Emacs, replace the placeholder ~[yourname]~ at the top of this
   file by your own name and write ~(pledged)~ next to it
2) Go with the cursor on the headline and hange the ~TODO~ label to ~DONE~
   by entering ~S-<right>~ ("Shift + right-arrow").

* TODO Saving, loading, removing R data structures

1) Copy the built-in data frame ~ToothGrowth~ to an R object ~df~ and
   display its structure.
   #+begin_src R 

   #+end_src

2) Save ~df~ to a (machine) file ~df.RData~ in the current directory.
   #+begin_src R :results silent

   #+end_src

3) Check that the file exists without leaving R.
   #+begin_src R

   #+end_src

4) Remove ~df~ from the current R session and check that it's been
   removed.
   #+begin_src R

   #+end_src

5) Load the dataframe from the file ~df.RData~.
   #+begin_src R

   #+end_src

6) You can save all data from your work session with ~save.image()~. The
   result will be saved in a file ~.RData~.
   1. Create ~x <- 1:100~, ~y <- c(TRUE,FALSE)~
   2. Run ~save.image()~ to save session to =.RData=
   3. Check that the file exists with the Linux command =ls= from R
   4. Check the file type with the Linux command =file= from R
   5. Remove all objects from your session with ~rm~ and check with ~ls~
   6. Load ~.RData~
   7. Check your session variable list with =ls=
   8. Print =x= and =y=
   #+begin_src R

   #+end_src

* TODO Importing data from CSV files

The (raw) file with patient data is available online here:
https://tinyurl.com/pt-data

1) Read the CSV file into a dataframe ~pt_data~, check its structure,
   and print the data.
   #+begin_src R

   #+end_src

2) What are the default parameters of ~read.csv~ regarding existence of
   a ~header~, the import of ~characters~ as ~factor~, and the =separator=?
   #+begin_src R

   #+end_src

3) Did you find any information on =factor= or =character= data? Find out
   how you can import the CSV data so that the =character= vectors are
   imported as =factor= vectors right away.

4) Re-import the CSV data with the =character= vectors as =factor= using
   =read.table= this time - fix errors if you notice any.
   #+begin_src R

   #+end_src
   
5) Using =write.csv=, write the dataframe ~pt_data~ to a CSV file
   ~pt_data.csv~ in your PC's ~Download~ directory (set the parameter
   ~row.names~ to =FALSE=), check that the file is there (from R), and
   check the file type, too. Then print the file - all from within R.
   #+begin_src R

   #+end_src


